id = "purple-theme"
name = "Purple Theme"
version = "0.0.1"
schema_version = 1
description = "Purple theme simple and readable"
repository = "https://github.com/AlessandroPerazzetta/zed-purple-theme"
authors = ["Alessandro Perazzetta"]
themes = ["themes/purple-theme.json"]
languages = []

[lib]

[grammars]

[language_servers]

[slash_commands]

[indexed_docs_providers]
